#include "TextRenderer.h"

#include <cstddef>

namespace TextRenderer
{

namespace
{

// One glyph = one ASCII character paired with its 8-row bitmap. Stored in an unordered table looked up linearly by
// glyphPattern(); the table is small (a few dozen entries) and the lookups happen at most once per drawn character,
// so the linear scan is the simplest correct option. A sorted table + std::lower_bound is an obvious future
// optimization; the data structure here was picked for legibility, not throughput.
//
// Bit convention (must match the documentation in TextRenderer.h): bit (kGlyphPixelCols - 1 - col) is column `col`,
// i.e. bit 3 is the leftmost column and the upper four bits of each row are always zero. Each binary literal therefore
// reads visually left-to-right like the rendered glyph -- `0b1001` is `#..#` (cols 0 and 3 on, cols 1 and 2 off).
//
// Digit-set design convention (0..9): pure straight-stroke 7-segment-style glyphs modeled on the original Atari Pong
// (1972) score readout, which was generated by discrete TTL logic and therefore had only full-row horizontal bars and
// 1-cell-wide vertical strokes -- no diagonals, no rounded corners. The seven segments map onto the 4x8 grid as:
//
//   row 0          ####    top horizontal
//   rows 1..2    #    #    top-left and top-right verticals  (cols 0 and 3)
//   row 3          ####    middle horizontal
//   rows 4..6    #    #    bottom-left and bottom-right verticals  (cols 0 and 3)
//   row 7          ####    bottom horizontal
//
// Because rows are 0/3/7 (not 0/4/7 -- 8 rows have no central row to mirror around), the top loop occupies rows 1..2
// (2 cells) and the bottom loop occupies rows 4..6 (3 cells). This naturally produces the "top smaller than bottom"
// asymmetry of reference Pong frames without any per-glyph special casing.
//
// Two intentional departures from a stock 7-segment display match the Pong digit ROM:
//   - `6` omits the top horizontal: the top-left vertical just ends at row 0 with no horizontal cap.
//   - `9` omits the bottom horizontal: the bottom-right vertical just ends at row 7 with no horizontal cap.
// The same logic gives `1` as a single vertical stroke down column 3 (rows 0..7, no horizontal caps anywhere) and
// `7` as the top bar plus a single descending right vertical, both matching reference frames.
//
// Menu-letter design convention (A, E, G, I, L, M, N, O, P, Q, R, S, T, U, V, Y): the original Atari Pong only ever
// rendered digits, so there is no equivalent historical reference for letters. They keep a looser layout that may
// use 2-cell tops, narrowing tapers (V, Y), and stair-step approximations for diagonals (N, R, Q's tail). Revisit
// when the menus milestone lands and reference frames for the menu text become the constraint.
struct Glyph
{
    char character;
    std::array<std::uint8_t, kGlyphPixelRows> rows;
};

// clang-format off
constexpr std::array<Glyph, 27> kGlyphs = {{
    {'0', {0b1111, 0b1001, 0b1001, 0b1001, 0b1001, 0b1001, 0b1001, 0b1111}},
    {'1', {0b0001, 0b0001, 0b0001, 0b0001, 0b0001, 0b0001, 0b0001, 0b0001}},
    {'2', {0b1111, 0b0001, 0b0001, 0b1111, 0b1000, 0b1000, 0b1000, 0b1111}},
    {'3', {0b1111, 0b0001, 0b0001, 0b1111, 0b0001, 0b0001, 0b0001, 0b1111}},
    {'4', {0b1001, 0b1001, 0b1001, 0b1111, 0b0001, 0b0001, 0b0001, 0b0001}},
    {'5', {0b1111, 0b1000, 0b1000, 0b1111, 0b0001, 0b0001, 0b0001, 0b1111}},
    {'6', {0b1000, 0b1000, 0b1000, 0b1111, 0b1001, 0b1001, 0b1001, 0b1111}},
    {'7', {0b1111, 0b0001, 0b0001, 0b0001, 0b0001, 0b0001, 0b0001, 0b0001}},
    {'8', {0b1111, 0b1001, 0b1001, 0b1111, 0b1001, 0b1001, 0b1001, 0b1111}},
    {'9', {0b1111, 0b1001, 0b1001, 0b1111, 0b0001, 0b0001, 0b0001, 0b0001}},
    {'A', {0b0110, 0b1001, 0b1001, 0b1111, 0b1001, 0b1001, 0b1001, 0b1001}},
    {'E', {0b1111, 0b1000, 0b1000, 0b1110, 0b1000, 0b1000, 0b1000, 0b1111}},
    {'G', {0b0110, 0b1001, 0b1000, 0b1011, 0b1001, 0b1001, 0b1001, 0b0110}},
    {'I', {0b1111, 0b0110, 0b0110, 0b0110, 0b0110, 0b0110, 0b0110, 0b1111}},
    {'L', {0b1000, 0b1000, 0b1000, 0b1000, 0b1000, 0b1000, 0b1000, 0b1111}},
    {'M', {0b1001, 0b1111, 0b1001, 0b1001, 0b1001, 0b1001, 0b1001, 0b1001}},
    {'N', {0b1001, 0b1101, 0b1101, 0b1011, 0b1011, 0b1001, 0b1001, 0b1001}},
    {'O', {0b1111, 0b1001, 0b1001, 0b1001, 0b1001, 0b1001, 0b1001, 0b1111}},
    {'P', {0b1111, 0b1001, 0b1110, 0b1000, 0b1000, 0b1000, 0b1000, 0b1000}},
    {'Q', {0b1111, 0b1001, 0b1001, 0b1001, 0b1001, 0b1011, 0b1111, 0b0011}},
    {'R', {0b1111, 0b1001, 0b1110, 0b1100, 0b1010, 0b1001, 0b1001, 0b1001}},
    {'S', {0b0111, 0b1000, 0b1000, 0b0110, 0b0001, 0b0001, 0b0001, 0b1110}},
    {'T', {0b1111, 0b0110, 0b0110, 0b0110, 0b0110, 0b0110, 0b0110, 0b0110}},
    {'U', {0b1001, 0b1001, 0b1001, 0b1001, 0b1001, 0b1001, 0b1001, 0b1111}},
    {'V', {0b1001, 0b1001, 0b1001, 0b1001, 0b0110, 0b0110, 0b0110, 0b0010}},
    {'Y', {0b1001, 0b0110, 0b0110, 0b0110, 0b0110, 0b0110, 0b0110, 0b0110}},
    {' ', {0b0000, 0b0000, 0b0000, 0b0000, 0b0000, 0b0000, 0b0000, 0b0000}},
}};
// clang-format on

constexpr std::array<std::uint8_t, kGlyphPixelRows> kBlankGlyph = {0, 0, 0, 0, 0, 0, 0, 0};

} // namespace

std::array<std::uint8_t, kGlyphPixelRows> glyphPattern(char c)
{
    for (const Glyph& g : kGlyphs)
    {
        if (g.character == c)
        {
            return g.rows;
        }
    }
    return kBlankGlyph;
}

std::vector<SDL_FRect> textGlyphRects(std::string_view text,
                                      float originX,
                                      float originY,
                                      float pixelSize,
                                      float glyphSpacing)
{
    std::vector<SDL_FRect> rects;
    if (text.empty() || pixelSize <= 0.0f)
    {
        return rects;
    }

    const float glyphWidth = static_cast<float>(kGlyphPixelCols) * pixelSize;
    const float glyphPitch = glyphWidth + glyphSpacing;

    // Upper-bound the rect count so the typical case avoids reallocations. Worst case is every pixel of every glyph
    // turned on (35 per glyph); the reserve cost is one allocation per call regardless of glyph density.
    rects.reserve(text.size() * static_cast<std::size_t>(kGlyphPixelCols * kGlyphPixelRows));

    for (std::size_t i = 0; i < text.size(); ++i)
    {
        const std::array<std::uint8_t, kGlyphPixelRows> pattern = glyphPattern(text[i]);
        const float glyphLeft = originX + static_cast<float>(i) * glyphPitch;
        for (int row = 0; row < kGlyphPixelRows; ++row)
        {
            const std::uint8_t rowBits = pattern[row];
            if (rowBits == 0)
            {
                continue;
            }
            for (int col = 0; col < kGlyphPixelCols; ++col)
            {
                const unsigned int mask = 1u << static_cast<unsigned int>(kGlyphPixelCols - 1 - col);
                if ((rowBits & mask) != 0u)
                {
                    SDL_FRect rect{};
                    rect.x = glyphLeft + static_cast<float>(col) * pixelSize;
                    rect.y = originY + static_cast<float>(row) * pixelSize;
                    rect.w = pixelSize;
                    rect.h = pixelSize;
                    rects.push_back(rect);
                }
            }
        }
    }
    return rects;
}

void drawText(SDL_Renderer* renderer,
              std::string_view text,
              float originX,
              float originY,
              float pixelSize,
              float glyphSpacing)
{
    if (renderer == nullptr)
    {
        return;
    }
    const std::vector<SDL_FRect> rects = textGlyphRects(text, originX, originY, pixelSize, glyphSpacing);
    for (const SDL_FRect& rect : rects)
    {
        SDL_RenderFillRect(renderer, &rect);
    }
}

} // namespace TextRenderer
