#pragma once

#include <SDL3/SDL.h>

#include <array>
#include <cstdint>
#include <string_view>
#include <vector>

// Text rendering for the playfield score and the upcoming menu strings (PONG, PAUSE, GAME OVER, 1 PLAYER, 2 PLAYER,
// RESTART, QUIT).
//
// Chosen approach: a small hand-drawn 4x8 bitmap font modeled on classic arcade-Pong score readouts. Each glyph is a
// constexpr table of eight uint8_t rows, with bit (kGlyphPixelCols - 1 - col) representing the pixel at column `col`
// (bit 3 = leftmost column, bit 0 = rightmost; the upper four bits are always zero). `textGlyphRects` returns one
// SDL_FRect per on-pixel scaled by `pixelSize`, which the thin SDL boundary draws with SDL_RenderFillRect.
//
// Why 4x8 rather than the 5x7 grid the original ISSUES.md sketch suggested:
//   - The original Atari Pong (1972) score readout was generated by discrete TTL logic and rendered every digit with
//     full-row horizontal bars and 1-cell-wide vertical strokes only -- no diagonals, no rounded corners. The natural
//     home for that style is a 4x8 box laid out as a 7-segment display: horizontals at rows 0/3/7 and verticals down
//     columns 0 and 3. A 5x7 grid forces a center row that the original digit ROM did not use, and a wider column
//     count invites diagonal stair-steps that drift away from the reference look.
//   - With horizontal bars fixed at rows 0/3/7, the top loop occupies rows 1..2 (2 cells) and the bottom loop rows
//     4..6 (3 cells). The "top smaller than bottom" asymmetry that reference Pong frames are known for therefore
//     drops out of the geometry rather than being applied per glyph.
//   - Two Pong-specific quirks survive verbatim: `6` omits the top horizontal (the top-left vertical just ends at row
//     0 with no horizontal cap), `9` omits the bottom horizontal. `1` is a single vertical line down the right column.
//   - The menu-letter set (A, E, G, I, L, M, N, O, P, Q, R, S, T, U, V, Y) has no equivalent historical reference --
//     the original arcade hardware only rendered digits -- so the letters keep a looser style: 2-cell apex on A, M
//     drawn as a thick-top Pi, stair-step approximations of diagonals on N and R, narrowing tapers on V and Y. The
//     menus milestone will revisit them once reference frames for the menu text become the constraint.
//
// Why this approach, rejecting the two alternatives evaluated in docs/ISSUES.md:
//   - Hand-drawn 7-segment digits would have shipped a digits-only renderer that the Screens-and-menus milestone would
//     have had to throw away (menus need full words). The constant we save by going simpler now is paid back twice
//     when menus land.
//   - SDL3_ttf with a bundled TTF font would add a third-party dependency, CI dev-headers on Linux, an asset-path
//     resolution problem on three OSes, and a font-license note -- all for a fixed, small set of arcade strings.
//
// The glyph table covers `0..9` plus the menu alphabet (A, E, G, I, L, M, N, O, P, Q, R, S, T, U, V, Y) and `space`.
// It is intentionally easy to extend: add another entry to the kGlyphs table in TextRenderer.cpp; no signature changes.
namespace TextRenderer
{

// 4 columns x 8 rows per glyph. Both halves of the project (layout math and the SDL renderer) read these so that
// changing the grid dimension is a single-point edit.
constexpr int kGlyphPixelCols = 4;
constexpr int kGlyphPixelRows = 8;

// Bitmap for the given character. Each returned uint8_t encodes one row: bit (kGlyphPixelCols - 1 - col) is the pixel
// at column `col` (so bit 4 is the leftmost column, bit 0 the rightmost, and the upper three bits are always zero).
// Unsupported characters return an all-zero pattern; they still consume one glyph slot in textGlyphRects so the
// caller-visible layout stays consistent (useful for `space` and as a defensive fallback).
[[nodiscard]] std::array<std::uint8_t, kGlyphPixelRows> glyphPattern(char c);

// One SDL_FRect per on-pixel of `text` rendered at (`originX`, `originY`) with each font pixel scaled to a
// `pixelSize` x `pixelSize` square and `glyphSpacing` logical pixels between adjacent glyphs.
//
// Layout convention:
//   - Glyph i sits at originX + i * (kGlyphPixelCols * pixelSize + glyphSpacing), originY. Total text width is
//     therefore N * (kGlyphPixelCols * pixelSize + glyphSpacing) - glyphSpacing (no trailing spacing).
//   - Inside a glyph, row 0 is the top row and column 0 the leftmost; rects grow rightward and downward to match
//     SDL's screen-space convention (see Playfield.h).
//   - A `space` (or any unsupported character) contributes zero rects but still advances the layout by one glyph.
//
// Defensive behavior: an empty `text` or a non-positive `pixelSize` returns an empty vector instead of asserting,
// matching the centerDashSegments contract in PlayfieldLayout.
[[nodiscard]] std::vector<SDL_FRect> textGlyphRects(std::string_view text,
                                                    float originX,
                                                    float originY,
                                                    float pixelSize,
                                                    float glyphSpacing);

// Thin SDL boundary: computes the rects via textGlyphRects() and issues one SDL_RenderFillRect per rect. Does not
// touch the renderer's draw-color state, so the caller can set white once and draw paddles, ball, dashes, and text
// under the same setup (the same convention PlayfieldRenderer::draw follows).
//
// Not directly unit-tested: its behavior reduces to textGlyphRects() (covered by TextRendererTest) plus the SDL call,
// which would require an offscreen renderer harness to exercise meaningfully. Keep the function body trivial enough
// that visual inspection is the assurance.
void drawText(SDL_Renderer* renderer,
              std::string_view text,
              float originX,
              float originY,
              float pixelSize,
              float glyphSpacing);

} // namespace TextRenderer
